name: "Space Shuttle API Build and Deploy"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AZURE_WEBAPP_NAME: "spaceshuttleapi"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  NETCORE_VERSION: "3.1.405"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure WepApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
